USE nongnong_ecommerce;
START TRANSACTION;
UPDATE product_info SET product_img='/uploads/product-1-main-1.jpg,/uploads/product-1-main-2.jpg', product_detail_img='/uploads/product-1-detail-1.jpg,/uploads/product-1-detail-2.jpg' WHERE id=1;
UPDATE product_info SET product_img='/uploads/product-2-main-1.jpg,/uploads/product-2-main-2.jpg', product_detail_img='/uploads/product-2-detail-1.jpg,/uploads/product-2-detail-2.jpg' WHERE id=2;
UPDATE product_info SET product_img='/uploads/product-3-main-1.jpg,/uploads/product-3-main-2.jpg', product_detail_img='/uploads/product-3-detail-1.jpg,/uploads/product-3-detail-2.jpg' WHERE id=3;
UPDATE product_info SET product_img='/uploads/product-4-main-1.jpg,/uploads/product-4-main-2.jpg', product_detail_img='/uploads/product-4-detail-1.jpg,/uploads/product-4-detail-2.jpg' WHERE id=4;
UPDATE product_info SET product_img='/uploads/product-5-main-1.jpg,/uploads/product-5-main-2.jpg', product_detail_img='/uploads/product-5-detail-1.jpg,/uploads/product-5-detail-2.jpg' WHERE id=5;
UPDATE product_info SET product_img='/uploads/product-6-main-1.jpg,/uploads/product-6-main-2.jpg', product_detail_img='/uploads/product-6-detail-1.jpg,/uploads/product-6-detail-2.jpg' WHERE id=6;
UPDATE product_info SET product_img='/uploads/product-7-main-1.jpg,/uploads/product-7-main-2.jpg', product_detail_img='/uploads/product-7-detail-1.jpg,/uploads/product-7-detail-2.jpg' WHERE id=7;
UPDATE product_info SET product_img='/uploads/product-8-main-1.jpg,/uploads/product-8-main-2.jpg', product_detail_img='/uploads/product-8-detail-1.jpg,/uploads/product-8-detail-2.jpg' WHERE id=8;
UPDATE product_info SET product_img='/uploads/product-16-main-1.jpg,/uploads/product-16-main-2.jpg', product_detail_img='/uploads/product-16-detail-1.jpg,/uploads/product-16-detail-2.jpg' WHERE id=16;
UPDATE product_info SET product_img='/uploads/product-17-main-1.jpg,/uploads/product-17-main-2.jpg', product_detail_img='/uploads/product-17-detail-1.jpg,/uploads/product-17-detail-2.jpg' WHERE id=17;
UPDATE product_info SET product_img='/uploads/product-21-main-1.jpg,/uploads/product-21-main-2.jpg', product_detail_img='/uploads/product-21-detail-1.jpg,/uploads/product-21-detail-2.jpg' WHERE id=21;
UPDATE product_info SET product_img='/uploads/product-22-main-1.jpg,/uploads/product-22-main-2.jpg', product_detail_img='/uploads/product-22-detail-1.jpg,/uploads/product-22-detail-2.jpg' WHERE id=22;
UPDATE product_info SET product_img='/uploads/product-23-main-1.jpg,/uploads/product-23-main-2.jpg', product_detail_img='/uploads/product-23-detail-1.jpg,/uploads/product-23-detail-2.jpg' WHERE id=23;
UPDATE product_info SET product_img='/uploads/product-24-main-1.jpg,/uploads/product-24-main-2.jpg', product_detail_img='/uploads/product-24-detail-1.jpg,/uploads/product-24-detail-2.jpg' WHERE id=24;
UPDATE product_info SET product_img='/uploads/product-25-main-1.jpg,/uploads/product-25-main-2.jpg', product_detail_img='/uploads/product-25-detail-1.jpg,/uploads/product-25-detail-2.jpg' WHERE id=25;
UPDATE product_info SET product_img='/uploads/product-26-main-1.jpg,/uploads/product-26-main-2.jpg', product_detail_img='/uploads/product-26-detail-1.jpg,/uploads/product-26-detail-2.jpg' WHERE id=26;
UPDATE product_info SET product_img='/uploads/product-27-main-1.jpg,/uploads/product-27-main-2.jpg', product_detail_img='/uploads/product-27-detail-1.jpg,/uploads/product-27-detail-2.jpg' WHERE id=27;
UPDATE product_info SET product_img='/uploads/product-28-main-1.jpg,/uploads/product-28-main-2.jpg', product_detail_img='/uploads/product-28-detail-1.jpg,/uploads/product-28-detail-2.jpg' WHERE id=28;
UPDATE product_info SET product_img='/uploads/product-29-main-1.jpg,/uploads/product-29-main-2.jpg', product_detail_img='/uploads/product-29-detail-1.jpg,/uploads/product-29-detail-2.jpg' WHERE id=29;
UPDATE product_info SET product_img='/uploads/product-30-main-1.jpg,/uploads/product-30-main-2.jpg', product_detail_img='/uploads/product-30-detail-1.jpg,/uploads/product-30-detail-2.jpg' WHERE id=30;
UPDATE product_info SET product_img='/uploads/product-31-main-1.jpg,/uploads/product-31-main-2.jpg', product_detail_img='/uploads/product-31-detail-1.jpg,/uploads/product-31-detail-2.jpg' WHERE id=31;
UPDATE product_info SET product_img='/uploads/product-32-main-1.jpg,/uploads/product-32-main-2.jpg', product_detail_img='/uploads/product-32-detail-1.jpg,/uploads/product-32-detail-2.jpg' WHERE id=32;
UPDATE product_info SET product_img='/uploads/product-33-main-1.jpg,/uploads/product-33-main-2.jpg', product_detail_img='/uploads/product-33-detail-1.jpg,/uploads/product-33-detail-2.jpg' WHERE id=33;
UPDATE product_info SET product_img='/uploads/product-34-main-1.jpg,/uploads/product-34-main-2.jpg', product_detail_img='/uploads/product-34-detail-1.jpg,/uploads/product-34-detail-2.jpg' WHERE id=34;
UPDATE product_info SET product_img='/uploads/product-35-main-1.jpg,/uploads/product-35-main-2.jpg', product_detail_img='/uploads/product-35-detail-1.jpg,/uploads/product-35-detail-2.jpg' WHERE id=35;
UPDATE product_info SET product_img='/uploads/product-36-main-1.jpg,/uploads/product-36-main-2.jpg', product_detail_img='/uploads/product-36-detail-1.jpg,/uploads/product-36-detail-2.jpg' WHERE id=36;
UPDATE product_info SET product_img='/uploads/product-37-main-1.jpg,/uploads/product-37-main-2.jpg', product_detail_img='/uploads/product-37-detail-1.jpg,/uploads/product-37-detail-2.jpg' WHERE id=37;
UPDATE product_info SET product_img='/uploads/product-38-main-1.jpg,/uploads/product-38-main-2.jpg', product_detail_img='/uploads/product-38-detail-1.jpg,/uploads/product-38-detail-2.jpg' WHERE id=38;
UPDATE product_info SET product_img='/uploads/product-39-main-1.jpg,/uploads/product-39-main-2.jpg', product_detail_img='/uploads/product-39-detail-1.jpg,/uploads/product-39-detail-2.jpg' WHERE id=39;
UPDATE product_info SET product_img='/uploads/product-40-main-1.jpg,/uploads/product-40-main-2.jpg', product_detail_img='/uploads/product-40-detail-1.jpg,/uploads/product-40-detail-2.jpg' WHERE id=40;
UPDATE product_info SET product_img='/uploads/product-41-main-1.jpg,/uploads/product-41-main-2.jpg', product_detail_img='/uploads/product-41-detail-1.jpg,/uploads/product-41-detail-2.jpg' WHERE id=41;
UPDATE product_info SET product_img='/uploads/product-42-main-1.jpg,/uploads/product-42-main-2.jpg', product_detail_img='/uploads/product-42-detail-1.jpg,/uploads/product-42-detail-2.jpg' WHERE id=42;
UPDATE product_info SET product_img='/uploads/product-43-main-1.jpg,/uploads/product-43-main-2.jpg', product_detail_img='/uploads/product-43-detail-1.jpg,/uploads/product-43-detail-2.jpg' WHERE id=43;
UPDATE product_info SET product_img='/uploads/product-44-main-1.jpg,/uploads/product-44-main-2.jpg', product_detail_img='/uploads/product-44-detail-1.jpg,/uploads/product-44-detail-2.jpg' WHERE id=44;
COMMIT;
